import { BrowserWindow } from 'electron';
import isDev from 'electron-is-dev';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const createWindow = () => {
  // Create the browser window.
  const win = new BrowserWindow({
    width: 450,
    height: 510,
    backgroundColor: '#252a2e',
    transparent: false,
    frame: false,
    show: false,
    resizable: true,
    fullscreenable: false,
    alwaysOnTop: true,
    roundedCorners: true,
    skipTaskbar: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      webSecurity: isDev ? false : true
    },
  });

  // and load the index.html of the app.
  win.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  win.on('blur', () => {
    win.hide();
  });

  // Open the DevTools.
  isDev && win.webContents.openDevTools();
  return win;
}

export default createWindow;