name: Development Distribution - Build

on: [push, pull_request]

jobs:

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pronutrirAtendimentoMac
        path: out/make/zip/darwin/x64/

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pronutrirAtendimentoWin
        path: out/make/